# -*- coding: utf-8 -*-
"""Apuntes2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ok28Q0Qj75J7nXdrYQDbM7GMPyyPZDZK
"""

import streamlit as st
import pandas as pd

st.title("Police Incident Reports from 2018 to 2020 in San Francisco")

df= pd.read_csv("https://drive.google.com/file/d/11oLcKiW8SgCOp3tGiQCYuRG7pLL_J-Zf/view?usp=drive_link")

st.markdown("The data shown below belongs to incident reports in the city of San Francisco, from the year 2018 to 2020, with details from each case such as date, day of the week, police district, neighborhood in which it happened, type of incident in category and subcategory, exact location and resolution.")

# Coordenadas de San Francisco
sf_lat = 37.7749
sf_lon = -122.4194

# Crear un DataFrame con las coordenadas de San Francisco
sf_df = pd.DataFrame({'lat': [sf_lat], 'lon': [sf_lon]})

# Mostrar el mapa de San Francisco con un marcador en la ubicación
st.map(sf_df, zoom=12)